import { Product, Category, Flavor, Promotion, StoreContent, StoreSettings } from './types';

export const DEFAULT_SETTINGS: StoreSettings = {
  id: 'singleton',
  storeName: 'KOUKOU Chocolatería',
  whatsappPhone: '528442924776',
  location: 'Saltillo, Coahuila, México',
  schedule: 'Lunes a Domingo: 10:00 - 21:00',
  instagram: 'https://www.instagram.com/koukou.choco.slw?stkn=bzJoNzR2OWMyMzA5',
  facebook: 'https://www.facebook.com/koukouchocolate',
  tiktok: 'https://www.tiktok.com/@koukouchocolate',
  currency: 'MXN',
  seoTitle: 'KOUKOU | Chocolatería de Alta Gama & Bonbons en Saltillo',
  seoDescription: 'Chocolates finos, bonbons artesanales rellenos, alfajores y café de especialidad en Saltillo.',
};

export const DEFAULT_CONTENT: StoreContent = {
  id: 'singleton',
  heroKicker: 'KOUKOU · CHOCOLATERÍA',
  heroTitle: 'Momentos chidos con una mordida.',
  heroDescription: 'Chocolate, café y repostería creados para convertir cualquier momento en algo especial.',
  heroImage: 'https://images.unsplash.com/photo-1575377427642-087cf684f29d?auto=format&fit=crop&w=1800&q=85',
  featureKicker: 'ESPECIALIDAD KOUKOU',
  featureTitle: 'Chocolate con personalidad.',
  featureDescription: 'Nuestros bonbons son el corazón de KOUKOU: pequeños chocolates rellenos creados para sorprender desde el primer mordisco.',
  featureImage: 'https://images.unsplash.com/photo-1548907040-4baa42d10919?auto=format&fit=crop&w=1200&q=85',
  bannerKicker: 'KOUKOU MOMENTS',
  bannerTitle: 'Un chocolate. Un momento.',
  bannerDescription: 'Regala, comparte o simplemente date el gusto.',
  bannerImage: 'https://images.unsplash.com/photo-1578985545062-69928b1d9587?auto=format&fit=crop&w=1600&q=85',
};

export const DEFAULT_CATEGORIES: Category[] = [
  { id: 'chocolates', slug: 'chocolates', name: 'Chocolates & Bonbons', icon: '🍫', order: 1, active: true },
  { id: 'reposteria', slug: 'reposteria', name: 'Repostería & Alfajores', icon: '🍰', order: 2, active: true },
  { id: 'cafe', slug: 'cafe', name: 'Café & Frappé', icon: '☕', order: 3, active: true },
  { id: 'barras', slug: 'barras', name: 'Barras Artesanales', icon: '🍫', order: 4, active: true },
  { id: 'especiales', slug: 'especiales', name: 'Especiales & Regalos', icon: '✨', order: 5, active: true },
];

export const DEFAULT_FLAVORS: Flavor[] = [
  { id: 'fl-1', name: 'Pimienta', category: 'Bonbon', description: 'Toque audaz de pimienta rosa sobre cacao profundo', intensity: 'Intenso', sweetness: 'Bajo', isNew: false, active: true },
  { id: 'fl-2', name: 'Vainilla', category: 'Bonbon', description: 'Vainilla natural Bourbon con textura aterciopelada', intensity: 'Suave', sweetness: 'Equilibrado', isNew: false, active: true },
  { id: 'fl-3', name: 'Leche quemada', category: 'Bonbon', description: 'Tradición con cajeta suave y cacao fino', intensity: 'Medio', sweetness: 'Dulce', isNew: false, active: true },
  { id: 'fl-4', name: 'Tocino', category: 'Bonbon', description: 'Crujiente balance dulce-salado con reducción ahumada', intensity: 'Intenso', sweetness: 'Equilibrado', isNew: true, active: true },
  { id: 'fl-5', name: 'Carajillo', category: 'Bonbon', description: 'Licor del 43 y espresso recién extraído', intensity: 'Intenso', sweetness: 'Equilibrado', isNew: false, active: true },
  { id: 'fl-6', name: 'Café', category: 'Bonbon', description: 'Intensa ganache con granos de café de altura', intensity: 'Medio', sweetness: 'Equilibrado', isNew: false, active: true },
  { id: 'fl-7', name: 'Caramelo', category: 'Bonbon', description: 'Caramelo de mantequilla y sal de manantial', intensity: 'Medio', sweetness: 'Dulce', isNew: false, active: true },
  { id: 'fl-8', name: 'Chai', category: 'Bonbon', description: 'Canela, cardamomo, clavo y jengibre perfumado', intensity: 'Medio', sweetness: 'Equilibrado', isNew: false, active: true },
  { id: 'fl-9', name: 'Whiskey Manzana', category: 'Bonbon', description: 'Destilado de roble con compota dulce de manzana', intensity: 'Intenso', sweetness: 'Equilibrado', isNew: true, active: true },
  { id: 'fl-10', name: 'Maracuyá', category: 'Bonbon', description: 'Acidez tropical envuelta en chocolate oscuro al 70%', intensity: 'Intenso', sweetness: 'Bajo', isNew: false, active: true },
];

export const DEFAULT_PRODUCTS: Product[] = [
  {
    id: 'prod-1',
    slug: 'caja-bonbons-6',
    name: 'Caja Bonbons KOUKOU (6 pzas)',
    categoryId: 'chocolates',
    price: 210,
    comparePrice: 260,
    stock: 45,
    image: 'https://images.unsplash.com/photo-1549007994-cb92caebd54b?auto=format&fit=crop&w=800&q=80',
    description: 'Nuestra icónica caja personalizada de 6 bonbons artesanales rellenos. Elige tus sabores favoritos o déjate sorprender.',
    featured: true,
    active: true,
    rating: 5.0,
    badge: 'Más Vendido',
    allowedFlavors: 'Pimienta,Vainilla,Leche quemada,Tocino,Carajillo,Café,Caramelo,Chai,Whiskey Manzana,Maracuyá',
  },
  {
    id: 'prod-2',
    slug: 'caja-bonbons-12',
    name: 'Caja Bonbons KOUKOU (12 pzas)',
    categoryId: 'chocolates',
    price: 390,
    comparePrice: 460,
    stock: 30,
    image: 'https://images.unsplash.com/photo-1575377427642-087cf684f29d?auto=format&fit=crop&w=800&q=80',
    description: 'El regalo definitivo para los amantes del buen chocolate. Caja rígida de lujo con 12 piezas de nuestra colección exclusiva.',
    featured: true,
    active: true,
    rating: 5.0,
    badge: 'Edición Regalo',
    allowedFlavors: 'Pimienta,Vainilla,Leche quemada,Tocino,Carajillo,Café,Caramelo,Chai,Whiskey Manzana,Maracuyá',
  },
  {
    id: 'prod-3',
    slug: 'bonbon-carajillo',
    name: 'Bonbon Carajillo',
    categoryId: 'chocolates',
    price: 35,
    stock: 80,
    image: 'https://images.unsplash.com/photo-1575377427642-087cf684f29d?auto=format&fit=crop&w=800&q=80',
    description: 'Chocolate relleno con notas seductoras de café espresso tostado y Licor 43 en equilibrio perfecto.',
    featured: true,
    active: true,
    rating: 4.9,
    badge: 'Favorito',
    allowedFlavors: 'Carajillo',
  },
  {
    id: 'prod-4',
    slug: 'bonbon-leche-quemada',
    name: 'Bonbon Leche Quemada',
    categoryId: 'chocolates',
    price: 35,
    stock: 90,
    image: 'https://images.unsplash.com/photo-1578985545062-69928b1d9587?auto=format&fit=crop&w=800&q=80',
    description: 'Chocolate con relleno cremoso y meloso de leche quemada artesanal al estilo norestense.',
    featured: true,
    active: true,
    rating: 5.0,
    badge: 'Tradición',
    allowedFlavors: 'Leche quemada',
  },
  {
    id: 'prod-5',
    slug: 'bonbon-whiskey-manzana',
    name: 'Bonbon Whiskey Manzana',
    categoryId: 'chocolates',
    price: 38,
    stock: 60,
    image: 'https://images.unsplash.com/photo-1549007994-cb92caebd54b?auto=format&fit=crop&w=800&q=80',
    description: 'Notas amaderadas de bourbon añejo combinadas con una reducción compotada de manzana especiada.',
    featured: false,
    active: true,
    rating: 4.8,
    badge: 'Nuevo',
    allowedFlavors: 'Whiskey Manzana',
  },
  {
    id: 'prod-6',
    slug: 'alfajor-koukou-clasico',
    name: 'Alfajor KOUKOU Clásico (Douce)',
    categoryId: 'reposteria',
    price: 48,
    stock: 50,
    image: 'https://images.unsplash.com/photo-1558961363-fa8fdf82db35?auto=format&fit=crop&w=800&q=80',
    description: 'Masa suave de mantequilla horneada al punto exacto, rellena con abundante dulce de leche y baño de chocolate semiamargo.',
    featured: true,
    active: true,
    rating: 4.9,
    badge: 'Top Ventas',
  },
  {
    id: 'prod-7',
    slug: 'alfajor-chocolate-blanco-nuez',
    name: 'Alfajor Chocolate Blanco y Nuez',
    categoryId: 'reposteria',
    price: 52,
    stock: 40,
    image: 'https://images.unsplash.com/photo-1558961363-fa8fdf82db35?auto=format&fit=crop&w=800&q=80',
    description: 'Doble galleta artesanal rellena con dulce de leche casero y cubierta con ganache de chocolate blanco y tropezones de nuez.',
    featured: false,
    active: true,
    rating: 4.9,
  },
  {
    id: 'prod-8',
    slug: 'cheesecake-cacao',
    name: 'Cheesecake KOUKOU Cacao',
    categoryId: 'reposteria',
    price: 75,
    stock: 25,
    image: 'https://images.unsplash.com/photo-1565958011703-44f9829ba187?auto=format&fit=crop&w=800&q=80',
    description: 'Cheesecake cremoso estilo New York infusionado con un remolino de ganache de cacao 70% y base crujiente de galleta KOUKOU.',
    featured: false,
    active: true,
    rating: 4.7,
  },
  {
    id: 'prod-9',
    slug: 'carrot-cake-especial',
    name: 'Carrot Cake Artesanal',
    categoryId: 'reposteria',
    price: 70,
    stock: 20,
    image: 'https://images.unsplash.com/photo-1599785209707-a456fc1337bb?auto=format&fit=crop&w=800&q=80',
    description: 'Bizcocho especiado con zanahorias frescas, canela fina, nuez pecanera y suave glaseado de queso crema.',
    featured: false,
    active: true,
    rating: 4.8,
  },
  {
    id: 'prod-10',
    slug: 'macarones-seleccion',
    name: 'Selección de Macarones (4 piezas)',
    categoryId: 'reposteria',
    price: 95,
    stock: 35,
    image: 'https://images.unsplash.com/photo-1558326567-98ae2405596b?auto=format&fit=crop&w=800&q=80',
    description: 'Caja con cuatro macarones franceses elaborados con harina de almendra: Chocolate oscuro, Pistache, Frambuesa y Café.',
    featured: false,
    active: true,
    rating: 4.9,
  },
  {
    id: 'prod-11',
    slug: 'galletas-koukou-cacao',
    name: 'Galletas KOUKOU Chispas Cacao',
    categoryId: 'reposteria',
    price: 55,
    stock: 60,
    image: 'https://images.unsplash.com/photo-1499636136210-6f4ee915583e?auto=format&fit=crop&w=800&q=80',
    description: 'Galletas horneadas diariamente con trozos generosos de chocolate real al 70% y un toque sutil de flor de sal.',
    featured: false,
    active: true,
    rating: 5.0,
    badge: 'Recién Horneadas',
  },
  {
    id: 'prod-12',
    slug: 'espresso-doble-origen',
    name: 'Espresso de Origen Doble',
    categoryId: 'cafe',
    price: 45,
    stock: 100,
    image: 'https://images.unsplash.com/photo-1510707577719-ae7c14805e3a?auto=format&fit=crop&w=800&q=80',
    description: 'Café de especialidad mexicano con tueste medio, notas a frutos secos y cacao dulce.',
    featured: false,
    active: true,
    rating: 4.8,
  },
  {
    id: 'prod-13',
    slug: 'frappe-koukou-mocha',
    name: 'Frappé KOUKOU Mocha Artesanal',
    categoryId: 'cafe',
    price: 65,
    stock: 75,
    image: 'https://images.unsplash.com/photo-1572490122747-3968b75cc699?auto=format&fit=crop&w=800&q=80',
    description: 'Frappé ultracremoso preparado con nuestra mezcla de chocolate semiamargo derretido y shot de espresso fresco.',
    featured: true,
    active: true,
    rating: 5.0,
    badge: 'Especial de Casa',
  },
  {
    id: 'prod-14',
    slug: 'sandwich-helado-cacao',
    name: 'Sándwich de Helado con Galleta de Cacao',
    categoryId: 'especiales',
    price: 70,
    stock: 30,
    image: 'https://images.unsplash.com/photo-1563805042-7684c019e1cb?auto=format&fit=crop&w=800&q=80',
    description: 'Helado artesanal de vainilla natural aprisionado entre dos galletas tiernas de chocolate intenso.',
    featured: true,
    active: true,
    rating: 4.9,
    badge: 'Especial',
  },
  {
    id: 'prod-15',
    slug: 'barra-cacao-70',
    name: 'Barra Cacao 70% de Origen',
    categoryId: 'barras',
    price: 90,
    stock: 45,
    image: 'https://images.unsplash.com/photo-1606312619070-d48b4c652a52?auto=format&fit=crop&w=800&q=80',
    description: 'Barra artesanal moldeada con cacao seleccionado de Soconusco, fermentado y tostado lentamente.',
    featured: true,
    active: true,
    rating: 5.0,
    badge: 'Bean to Bar',
  },
  {
    id: 'prod-16',
    slug: 'barra-chocolate-sal-mar',
    name: 'Barra Oscura con Sal de Mar',
    categoryId: 'barras',
    price: 95,
    stock: 40,
    image: 'https://images.unsplash.com/photo-1606312619070-d48b4c652a52?auto=format&fit=crop&w=800&q=80',
    description: 'Cacao oscuro 65% acentuado con cristales crujientes de sal de Colima recolectada artesanalmente.',
    featured: false,
    active: true,
    rating: 4.9,
  },
  {
    id: 'prod-17',
    slug: 'pack-cumpleanos-dulce',
    name: 'Pack Cumpleaños Dulce Momento',
    categoryId: 'especiales',
    price: 380,
    comparePrice: 420,
    stock: 20,
    image: 'https://images.unsplash.com/photo-1519869325930-281384150729?auto=format&fit=crop&w=800&q=80',
    description: 'Incluye Caja de 6 Bonbons a elegir, 2 Alfajores KOUKOU, tarjeta personalizada con dedicatoria y lazo festivo.',
    featured: true,
    active: true,
    rating: 5.0,
    badge: 'Pack Regalo',
  },
];

export const DEFAULT_PROMOTIONS: Promotion[] = [
  {
    id: 'promo-1',
    title: 'Bonbons KOUKOU',
    subtitle: 'Descubre nuestros rellenos exóticos.',
    kicker: 'COLECCIÓN EXCLUSIVA',
    buttonText: 'VER CHOCOLATES',
    buttonLink: '#productos',
    image: 'https://images.unsplash.com/photo-1549007994-cb92caebd54b?auto=format&fit=crop&w=800&q=80',
    isDark: true,
    active: true,
    order: 1,
  },
  {
    id: 'promo-2',
    title: 'Repostería & Alfajores',
    subtitle: 'Un antojo merece algo especial.',
    kicker: 'HORNEADO HOY',
    buttonText: 'DESCUBRIR',
    buttonLink: '#productos',
    image: 'https://images.unsplash.com/photo-1519869325930-281384150729?auto=format&fit=crop&w=800&q=80',
    isDark: true,
    active: true,
    order: 2,
  },
  {
    id: 'promo-3',
    title: 'Café & Frappé',
    subtitle: 'El complemento perfecto para tu chocolate.',
    kicker: 'ESPECIALIDAD',
    buttonText: 'VER MENÚ',
    buttonLink: '#productos',
    image: 'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?auto=format&fit=crop&w=800&q=80',
    isDark: true,
    active: true,
    order: 3,
  },
];
